spring.application.name=shorturl
# Habilitar la consola web de la base de datos H2
spring.h2.console.enabled=true
# La URL para acceder a la base de datos en memoria
spring.datasource.url=jdbc:h2:mem:shorturldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hace que Hibernate cree las tablas automáticamente basándose en nuestro código Java
spring.jpa.hibernate.ddl-auto=update
# Muestra en la consola de IntelliJ las consultas SQL reales que se están haciendo
spring.jpa.show-sql=true